### ISSUE TITLE
USDC transactions are being skipped

### ISSUE THREAD

**Issue by JMoli** [amacneil/cryptogains#42]
USDC transactions are being skipped on gdax (and coinbase, not sure how much that matters)

**Comment by JMoli** [comment]
I had to add a backfiller for usdc transactions and bump the toFixed(2) to toFixed(6) in the models transactions to get this to work.

**Comment by amacneil** [comment]
Please feel free to fork and modify cryptogains for your own needs like this. I don't intend for this to be a community project beyond publishing what has worked for me (and I personally intend to migrate over to one of the many commercial services which exist now, because keeping this software up to date with various API changes & forks is more effort than I desire).
