### ISSUE TITLE
Error: please fix these unreconciled transactions

### ISSUE THREAD

**Issue by nengine** [amacneil/cryptogains#8]
Hello, Could you please let me know what should I do after getting this "Error: please fix these unreconciled transactions" message?  Those are the external transfers sent/receive in GDAX which seems to be correct, but no sure what do with it.  Thanks a lot.

**Comment by nengine** [comment]
BTW, Thanks for making this. This is really cool.

**Comment by amacneil** [comment]
Hi - sorry this error isn't very helpful.

It's important to differentiate between transfers and a buy/sell/send/receive, because the former has no tax treatment (you still own the coins), and the latter is either an acquisition or a disposal.

If you're seeing this error on GDAX transfers, I'm guessing it is because you haven't imported the corresponding Coinbase transactions (if the coins were transferred to Coinbase, which all GDAX sends 
& receives do).

**Comment by nengine** [comment]
Thanks for taking take to answer.  If the BTC was bought in GDAX and sent to Bittrex to buy altcoin should it be considered as 'transfer' or 'send' type? I will try importing coinbase too.

**Comment by nengine** [comment]
Imported coinbase data and it is working now.  I wish I could be smart like you.  I am sure how to deal with Bittrex transactions though.   Many thanks.
